server:
  address: 0.0.0.0
  port: 8080
springdoc:
  api-docs:
    path: /api-documentation
  remove-broken-reference-definitions: false
spring:
  data:
    mongodb:
      port: 27017
      authentication-database: admin
      username: '${MONGO_USERNAME:user}'
      host: '${MONGO_HOST:localhost}'
