#mongo
#helm install mongodb bitnami/mongodb --set auth.enabled=false,,persistence.size=1Gi,architecture=replicaset,replicaCount=2
apiVersion: apps/v1
kind: Deployment
metadata:
  name: generating-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      component: generator
  template:
    metadata:
      labels:
        component: generator
    spec: 
      containers:
        - name: generating
          image: dominikoman16/task1
          imagePullPolicy: Always 
          ports:
          - containerPort: 8080
          env:
          - name: MONGO_USERNAME
            value: root
          - name: MONGO_HOST
            value: mongodb
